---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-app
data:
  mysql-password: MTIzNDU2
  mysql-root-password: "bXlzcWxyb290"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flask-app
data:
  mysql-db-name: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: flask-app
  labels:
    app: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8
        imagePullPolicy: IfNotPresent
        env:
        - name: "MYSQL_USER"
          value: user
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: "MYSQL_DATABASE"
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-db-name
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql-container
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: flask-app
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
    targetPort: mysql-container
  selector:
    app: mysql
  type: LoadBalancer